/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pboii;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hensu
 */
public class flaporan_penjualan_hendy extends javax.swing.JFrame {

    /**
     * Creates new form flaporan_penjualan
     */
    public flaporan_penjualan_hendy() {
        initComponents();
        laporanPenjualan();
    }

    private void laporanPenjualan() {
        DefaultTableModel modelPenjualan = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Menambahkan kolom ke model tabel
        modelPenjualan.addColumn("No Faktur");
        modelPenjualan.addColumn("Kode Barang");
        modelPenjualan.addColumn("Nama Barang");
        modelPenjualan.addColumn("Harga Satuan");
        modelPenjualan.addColumn("Jumlah Jual");
        modelPenjualan.addColumn("Total Harga Jual");
        modelPenjualan.addColumn("Tanggal");

        tabelPenjualan.setModel(modelPenjualan);
        int totalHargaTerjual = 0;

        try {
            Connection connection = koneksi.getKoneksi();
            Statement statement = connection.createStatement();

            String queryStokMasuk = "SELECT nofaktur, kd_barang, nama_barang, hsatuan, jumlah_jual, (hsatuan * jumlah_jual) AS total_harga_jual, tanggal FROM tbl_penjualan";
            ResultSet resultSet = statement.executeQuery(queryStokMasuk);

            // Menambahkan data ke model tabel
            while (resultSet.next()) {
                int totalHargaJual = resultSet.getInt("total_harga_jual");
                totalHargaTerjual += totalHargaJual; // Menambahkan ke total harga terjual

                modelPenjualan.addRow(new Object[]{
                    resultSet.getString("nofaktur"),
                    resultSet.getString("kd_barang"),
                    resultSet.getString("nama_barang"),
                    resultSet.getInt("hsatuan"),
                    resultSet.getInt("jumlah_jual"),
                    totalHargaJual,
                    resultSet.getDate("tanggal")
                });
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error retrieving data from database.", "Database Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            ttotal.setText("" + totalHargaTerjual); // Menampilkan total harga terjual
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPenjualan = new javax.swing.JTable();
        ttotal = new javax.swing.JLabel();
        Total1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Laporan Penjualan");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Laporan Penjualan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 60));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelPenjualan.setAutoCreateRowSorter(true);
        tabelPenjualan.setBackground(new java.awt.Color(255, 255, 204));
        tabelPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelPenjualan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 720, 300));

        ttotal.setBackground(new java.awt.Color(153, 153, 153));
        ttotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ttotal.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(ttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, 30));

        Total1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Total1.setForeground(new java.awt.Color(255, 255, 255));
        Total1.setText("Total");
        jPanel2.add(Total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 770, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fmenu_hendy fb = new fmenu_hendy();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(flaporan_penjualan_hendy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(flaporan_penjualan_hendy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(flaporan_penjualan_hendy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(flaporan_penjualan_hendy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new flaporan_penjualan_hendy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelPenjualan;
    private javax.swing.JLabel ttotal;
    // End of variables declaration//GEN-END:variables
}
