package pboii;

import java.awt.Desktop;
import java.net.URL;

/**
 *
 * @author hensu
 */
public class fmenu_hendy extends javax.swing.JFrame {

    /**
     * Creates new form fmenu
     */
    public fmenu_hendy() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMaster = new javax.swing.JMenu();
        menuPegawai = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuBarang = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuPenjualan = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuLaporanStok = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuLaporanPenjualan = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));

        menuMaster.setForeground(new java.awt.Color(0, 0, 0));
        menuMaster.setText("Master");

        menuPegawai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPegawai.setText("Pegawai");
        menuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPegawaiActionPerformed(evt);
            }
        });
        menuMaster.add(menuPegawai);
        menuMaster.add(jSeparator1);

        menuBarang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuBarang.setText("Barang");
        menuBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBarangActionPerformed(evt);
            }
        });
        menuMaster.add(menuBarang);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setForeground(new java.awt.Color(0, 0, 0));
        menuTransaksi.setText("Transaksi");

        menuPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuPenjualan.setText("Penjualan");
        menuPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenjualanActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuPenjualan);

        jMenuBar1.add(menuTransaksi);

        menuLaporan.setForeground(new java.awt.Color(0, 0, 0));
        menuLaporan.setText("Laporan");

        menuLaporanStok.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLaporanStok.setText("Laporan Stok Barang");
        menuLaporanStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanStokActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLaporanStok);
        menuLaporan.add(jSeparator3);

        menuLaporanPenjualan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLaporanPenjualan.setText("Laporan Penjualan");
        menuLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanPenjualanActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLaporanPenjualan);

        jMenuBar1.add(menuLaporan);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarangActionPerformed
        // TODO add your handling code here:
        fbarang_hendy fb = new fbarang_hendy();
        fb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuBarangActionPerformed

    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenjualanActionPerformed
        // TODO add your handling code here:
        fpenjualan_hendy fp = new fpenjualan_hendy();
        fp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPenjualanActionPerformed

    private void menuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPegawaiActionPerformed
        // TODO add your handling code here:
        fpegawai_hendy ff = new fpegawai_hendy();
        ff.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuPegawaiActionPerformed

    private void menuLaporanStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanStokActionPerformed
        // TODO add your handling code here:
//        flaporan_stok_hendy fps = new flaporan_stok_hendy();
//        fps.setVisible(true);
//        this.setVisible(false);
        try {
            Desktop.getDesktop().browse(new URL("http://localhost/PenjualanBarang/src/laporanstokbarang.php").toURI());
        } catch (Exception e) {
            System.out.println("Failed to open browser: " + e);

            System.out.println("Opening URL in console: http://localhost/PenjualanBarang/src/laporanstokbarang.php");
        }
    }//GEN-LAST:event_menuLaporanStokActionPerformed

    private void menuLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanPenjualanActionPerformed
        // TODO add your handling code here:
//        flaporan_penjualan_hendy fjs = new flaporan_penjualan_hendy();
//        fjs.setVisible(true);
//        this.setVisible(false);
        try {
            Desktop.getDesktop().browse(new URL("http://localhost/PenjualanBarang/src/laporanpenjualan.php").toURI());
        } catch (Exception e) {
            System.out.println("Failed to open browser: " + e);

            System.out.println("Opening URL in console: http://localhost/PenjualanBarang/src/laporanpenjualan.php");
        }
    }//GEN-LAST:event_menuLaporanPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmenu_hendy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmenu_hendy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmenu_hendy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmenu_hendy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmenu_hendy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem menuBarang;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuLaporanPenjualan;
    private javax.swing.JMenuItem menuLaporanStok;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuPegawai;
    private javax.swing.JMenuItem menuPenjualan;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables

}
